AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: [RSpec.describe, context]

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
